// Generated by CoffeeScript 1.6.3
(function() {
  angular.module('myApp.filters', []).filter('reverse', function() {
    return function(text) {
      if (text) {
        return text.split("").reverse().join("");
      }
    };
  });

}).call(this);
