// Generated by CoffeeScript 1.6.3
(function() {
  services.factory('Tables', function() {
    var tables;
    tables = {};
    this.get = function() {
      var local_tables;
      local_tables = localStorage.getItem('tables');
      if (local_tables) {
        tables = JSON.parse(local_tables);
      }
      return tables;
    };
    this.put = function(tables) {
      return localStorage.setItem('tables', JSON.stringify(tables));
    };
    return {
      data: this.get(),
      put: this.put
    };
  });

  services.factory('Place', function() {
    var place;
    place = {};
    this.get = function() {
      var local_place;
      local_place = localStorage.getItem('place');
      if (local_place) {
        place = JSON.parse(local_place);
      }
      return place;
    };
    this.put = function(place) {
      return localStorage.setItem('place', JSON.stringify(place));
    };
    return {
      data: this.get(),
      put: this.put
    };
  });

  services.service('Data', function() {
    this.get = function() {
      return {
        message: "I'm data from a service"
      };
    };
    return this.get();
  });

}).call(this);
