// Generated by CoffeeScript 1.6.3
(function() {
  describe('controllers', function() {
    beforeEach(module('myApp.controllers'));
    return describe('FirstCtrl', function() {
      var scope;
      scope = null;
      beforeEach(inject(function($rootScope) {
        return scope = $rootScope.$new();
      }));
      return describe('the watch on foo', function() {
        return it('should fire when foo changes', inject(function($controller, $log) {
          spyOn($log, 'log');
          scope.$apply(function() {
            return $controller('FirstCtrl', {
              $scope: scope,
              $log: $log
            });
          });
          expect(scope.foo).toBe('bar');
          scope.$apply("foo = 'baz'");
          return expect(scope.foo).toBe('baz');
        }));
      });
    });
  });

}).call(this);
