// Generated by CoffeeScript 1.6.3
(function() {
  describe('filter', function() {
    beforeEach(module('myApp.filters'));
    return describe('reverse', function() {
      return it('should reverse a string', inject(function(reverseFilter) {
        return expect(reverseFilter('ABCD')).toEqual('DCBA');
      }));
    });
  });

}).call(this);
